// Gate: the newsletter popup's triggers, close paths, storage and validation.
import { browser, open, report } from './_lib.mjs';
const b = await browser();
let pg = await open(b, 1440, 900);
const early = await pg.evaluate(async () => { scrollTo(0, document.documentElement.scrollHeight); await new Promise(r => setTimeout(r, 1500)); return document.querySelector('#newsletterDialog').open; });
report('dialog: not before 10s even at 100% scroll', early === false);
await pg.evaluate(() => scrollTo(0, 0)); await pg.waitForTimeout(9000);
const shallow = await pg.evaluate(() => document.querySelector('#newsletterDialog').open);
report('dialog: not at 10s with <40% scroll', shallow === false);
await pg.evaluate(async () => { scrollTo(0, document.documentElement.scrollHeight * 0.5); }); await pg.waitForTimeout(2500);
const opened = await pg.evaluate(() => document.querySelector('#newsletterDialog').open);
report('dialog: opens once both hold', opened === true);
const focusOnHeading = await pg.evaluate(() => document.activeElement && document.activeElement.id === 'dialogTitle');
report('dialog: initial focus on the heading', focusOnHeading);
await pg.keyboard.press('Escape'); await pg.waitForTimeout(300);
const closed = await pg.evaluate(() => !document.querySelector('#newsletterDialog').open);
const stored = await pg.evaluate(() => localStorage.getItem('di:newsletter') || '');
report('dialog: Esc closes and records the dismissal', closed && stored.startsWith('dismissed:'), stored.slice(0, 20));
await pg.reload(); await pg.waitForTimeout(600);
await pg.evaluate(async () => { scrollTo(0, document.documentElement.scrollHeight * 0.6); }); await pg.waitForTimeout(11000);
const reopened = await pg.evaluate(() => document.querySelector('#newsletterDialog').open);
report('dialog: does not reopen after dismiss', reopened === false);
await pg.click('.nav__actions [data-open-dialog]'); await pg.waitForTimeout(300);
const manual = await pg.evaluate(() => document.querySelector('#newsletterDialog').open);
report('dialog: the nav button still opens it', manual === true);
await pg.fill('#dlg-email', 'not-an-email');
let requests = 0; pg.on('request', r => { if (r.method() === 'POST') requests++; });
await pg.click('#newsletterDialog button[type=submit]'); await pg.waitForTimeout(300);
const err = await pg.evaluate(() => document.querySelector('#newsletterDialog .field').classList.contains('is-error'));
report('dialog: rejects a bad email without a network call', err && requests === 0);
await pg.close();
pg = await open(b, 390, 844);
await pg.evaluate(() => { scrollTo(0, document.documentElement.scrollHeight * 0.5); }); await pg.waitForTimeout(11000);
const m = await pg.evaluate(() => { const d = document.querySelector('#newsletterDialog'); const before = scrollY; scrollBy(0, 40); return { open: d.open, modal: d.matches(':modal'), scrolled: scrollY !== before, height: d.getBoundingClientRect().height, vh: innerHeight }; });
report('dialog: mobile sheet is non-modal and ≤38vh', m.open && !m.modal && m.scrolled && m.height <= m.vh * 0.38 + 1, JSON.stringify(m));
await pg.close(); await b.close();
